### ISSUE TITLE
LTC点击充值或提现，右边为空白。

### ISSUE THREAD

**Issue by kokomoji** [blueplanet/peatio#11]
您好~ 
  请问一下这种情况该如何解决呢， 谢谢！

![ltc](https://user-images.githubusercontent.com/16488965/27819121-4f545a10-60cb-11e7-8575-748c61637a48.png)

**Comment by ShadowMyst** [comment]
ese mismo problema tengo yo

**Comment by ShadowMyst** [comment]
The solution is in public / template / funds. Creates a deposit_ltc.html and a withdraw_ltc.html

**Comment by kokomoji** [comment]
I added deposit_ltc.html and a withdraw_ltc.html, but the result is also empty , did i miss anything?
Thanks~

**Comment by ShadowMyst** [comment]
In the file deposit.html you need to add something like this:
<Ng-include ng-if = "currency == 'ltc'" src = "'/ templates / funds / deposit_ltc.html'"> </ ng-include> e same in the withdraw.html file

**Comment by kokomoji** [comment]
@ShadowMyst  It's working! 
Thanks for your help~

**Comment by blueplanet** [comment]
@ShadowMyst Thanks for you help~~ 👍 
@kokomoji You can close this problem?
