### ISSUE TITLE
注册后跳转的页面还是http://peatio.net/

### ISSUE THREAD

**Issue by y2kmz** [blueplanet/peatio#20]
用的是cloudea.club访问的系统，注册后跳转的页面还是http://peatio.net/
之后的页面迁移也都是http://peatio.net/

**Comment by blueplanet** [comment]
@y2kmz 这个应该是设置的问题。今天早上改了。现在应该没问题了。

**Comment by taylorshuang** [comment]
嘿嘿，不错啊，每天都有更新！
