### ISSUE TITLE
身份证件那一栏只有身份证和驾照，是说我们只面向国人吗？

### ISSUE THREAD

**Issue by y2kmz** [blueplanet/peatio#22]
身份证件那一栏只有身份证和驾照，是说我们只面向国人吗？
是不是应该加上
如果是别的国家的话：驾照，再留卡，护照均可？

**Comment by blueplanet** [comment]
@y2kmz 
这个我觉得可以暂时先保持现状。

最理想的完全的国际化对应的话，肯定是要用各个国家自己的身份验证机制，但那样的话对应的成本较高。
还可以采取一个折中方案，改成“身份证，驾照，护照”，然后把各个翻译改好。

@yanglinux 
怎么样？

**Comment by taylorshuang** [comment]
这个项目现在继承了eth了吧

**Comment by taylorshuang** [comment]
集成

**Comment by taylorshuang** [comment]
有时间我也加入一下，咱们基于这个做一个更多币种的
